# Generated by Django 5.1.3 on 2025-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='forget_token',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
