# Generated by Django 5.1.3 on 2025-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default="Hey there! I'm using Chatter", null=True),
        ),
    ]
