# Generated by Django 5.1.3 on 2025-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_message_delete_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_group_message',
            field=models.BooleanField(default=False),
        ),
    ]
