# Generated by Django 5.1.3 on 2025-04-17 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('ai_message_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ai_model', models.CharField(choices=[('DeepSeek-Paid', 'DEEPSEEK-R1:paid'), ('DeepSeek-Free', 'deepseek-r1-distill-llama-70b:free'), ('QWEN', 'QWEN-32b:free')], max_length=20)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
