# Generated by Django 5.1.3 on 2025-04-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='api_used',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
