# Generated by Django 5.1.3 on 2025-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_aichat_api_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichat',
            name='ai_model',
            field=models.CharField(choices=[('DeepSeek-Paid', 'DEEPSEEK-R1:paid'), ('DeepSeek-Free', 'deepseek-r1-distill-llama-70b:free'), ('QWEN', 'QWEN-32b:free')], max_length=200),
        ),
    ]
